# Book settings

title: Plants & Python
author: Dr. Dan Chitwood
logo: plants_python_logo.jpg

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: plants_and_python_book.tex

# Add a bibtex file so that we can create citations
#bibtex_bibfiles:
#  - pp_references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/PlantsAndPython/PlantsAndPython
#  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

# Add bottons to launch on Google Colab, binder
launch_buttons:
  colab_url: "https://colab.research.google.com"
  binderhub_url: "https://mybinder.org"
  thebe: true
